# Generated by Django 4.0.3 on 2022-04-04 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp_accession', models.CharField(max_length=10)),
                ('patient_id', models.CharField(max_length=10)),
                ('collection_date', models.DateField(verbose_name='date_collected')),
                ('specimen_type', models.CharField(max_length=100)),
                ('specimen_description', models.CharField(max_length=100)),
                ('morph_dx', models.CharField(max_length=250)),
                ('interpretation', models.TextField(max_length=500)),
                ('comment', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank', models.CharField(max_length=20)),
                ('rack', models.CharField(max_length=20)),
                ('pie', models.CharField(max_length=20)),
                ('cell_count', models.CharField(max_length=20)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample_management.sample')),
            ],
        ),
    ]
