# Generated by Django 4.0.3 on 2022-04-04 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('tank', 'rack', 'pie')},
        ),
    ]
